apiVersion: v1
kind: Service
metadata:
  name: esp-flask
spec:
  ports:
  - port: 5001
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: esp-flask
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esp-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: esp-flask
  template:
    metadata:
      labels:
        app: esp-flask
    spec:
      # [START secret-1]
      volumes:
        - name: endpoint-sa
          secret:
            secretName: endpoint-sa
      # [END secret-1]
      containers:
      # [START esp]
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:2
        imagePullPolicy: Always
        args: [
          "--listener_port=8081",
          "--backend=127.0.0.1:5000",
          "--service=api.endpoints.roava-io.cloud.goog",
          "--rollout_strategy=managed",
          "--dns=169.254.169.254",
          "--enable_debug",
          "--service_account_key=/etc/nginx/creds/endpoint-sa.json"
        ]
      # [END esp]
        ports:
          - containerPort: 8081

          # [START secret-2]
        volumeMounts:
          - mountPath: /etc/nginx/creds
            name: endpoint-sa
            readOnly: true
          # [END secret-2]

      - name: python-app
        image: barywhyte/pipe-demo:appv3
        imagePullPolicy: Always
        ports:
          - containerPort: 5000